### PR TITLE
Replay deepview request

### PR DESCRIPTION
**Pull request by derrickstaten**
@jsaleigh @dmitrig01

### CODE REVIEW

**Comment by jsaleigh** [comment]
👍  The failed check appears to be a SauceLabs issue

**Comment by yntema** [comment]
Working on getting the ci tests to pass. Nothing is broken, working on making a change to the tests right now.

**Comment by derrickstaten** [comment]
Okay. Please don't merge / release this just yet. It fixes one problem but amplifies another one, described in https://branch.atlassian.net/browse/INTENG-2842. So the order of operations, as specified on a different task (https://branch.atlassian.net/browse/INTENG-2841), is:

1. Dmitri makes change to matching service for INTENG-2842, then pushes live
2. Merge Web SDK PR 382, release web sdk
3. notify partners

**Comment by aaustin** [comment]
@derrickstaten We're ready for this guy to be fixed (merge conflicts) and deployed. Please drive it.

**Comment by derrickstaten** [comment]
@jsaleigh can you release this? I just fixed the merge conflicts. Thank you!

**Comment by yntema** [comment]
👍

**Pull request merged**
