### PR TITLE
WEBSDK-13 Allow callbacks for banner, setBranchViewData, and deepviewCTA

### PR DESCRIPTION
**Pull request by yntema**
This changes allows passing of a callback to methods that previously didn't allow them.

### CODE REVIEW

**Comment by kevinhylant** [comment]
+1

**Comment by yntema** [comment]
Looking into that right now 👀

**Comment by yntema** [comment]
Looks like it was due to the previous PR. Digging into it

**Comment by yntema** [comment]
Thanks for the heads up @kevinhylant

**Comment by jsaleigh** [comment]
👍

**Pull request merged**
